name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 3 * * 5"

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - AUR_PACKAGE: opendds
          - AUR_PACKAGE: opendds-git

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: ls
      run: ls -al

    - name: ls AUR_PACKAGE
      run: ls -al $AUR_PACKAGE

    - name: Build the Docker image
      run: docker build . --file Dockerfile --build-arg AUR_PACKAGE=$AUR_PACKAGE
